### ISSUE TITLE
Mod causes Build ID to change every time the game boots

### ISSUE THREAD

**Issue by SoulBlast35** [Lincoln-LM/swsh-mods-exl#10]
Im honestly not sure how to describe this, but every time the game boots with this mod installed, the build ID changes in Edizon, which means cheat codes dont work. Is this intentional or a by-product of how the mod works? Or is it an actual bug?

**Comment by Lincoln-LM** [comment]
i'm not sure how exactly build ids work but it's not unexpected that it would change when the mod adds a subsdk to the game. it seems weird that it keeps changing but yeah i would surmise that its a by-product of how the mod works

**Comment by SoulBlast35** [comment]
I think this actually causes Atmosphere to fatal if you have cheats installed and dont have the config set to disable them by default. Thanks for letting me know though.
