### ISSUE TITLE
Latest Release Doesn't Work

### ISSUE THREAD

**Issue by XModxGodX** [Lincoln-LM/swsh-mods-exl#11]
As soon as I boot the game it goes immediately to the game crash screen with the exefs files installed. I'm using real hardware with atmosphere on a cartridge version of Pokemon Sword with the latest version of the DLC and update. (1.3.2)

**Comment by Lincoln-LM** [comment]
are you on the latest version of atmosphere and do you have any cheats active or cheat software installed

**Comment by XModxGodX** [comment]
Looks like it was due to me using the same version of atmosphere for nearly a year.
