### ISSUE TITLE
Failed to read config

### ISSUE THREAD

**Issue by LilJohnnieGunns** [Lincoln-LM/swsh-mods-exl#14]
<img width="1213" alt="image" src="https://github.com/user-attachments/assets/c47b8ca1-847c-4634-8167-56413828235d" />

im not sure on how to get to the "sd" Directory at all

**Comment by Lincoln-LM** [comment]
> <img alt="image" width="1213" src="https://private-user-images.githubusercontent.com/83853286/398481478-c47b8ca1-847c-4634-8167-56413828235d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNzM0NDYsIm5iZiI6MTczNTA3MzE0NiwicGF0aCI6Ii84Mzg1MzI4Ni8zOTg0ODE0NzgtYzQ3YjhjYTEtODQ3Yy00NjM0LTgxNjctNTY0MTM4MjgyMzVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDIwNDU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjYjQ2ODVlZjgzMGJjYTAyMjgwNzExNWZkZDIxNDBmODIzNTVmODUzM2MwOTE5YzEzZWE3M2MzMzlmNGQ1YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uDpmoKOsaSj8qw_uV_mMQj6gb6YNnXhD8b3mVtcVUOM">
> 
> im not sure on how to get to the "sd" Directory at all

did you copy the "config" folder as mentioned in the readme? you can get to the sdcard folder (as mentioned there) by navigating a few folders up from where "Open Atmosphere Mods Directory" brings you
https://github.com/Lincoln-LM/swsh-mods-exl?tab=readme-ov-file#installation-ryujinx

**Comment by LilJohnnieGunns** [comment]
Thank you for telling me how to get to the sdcard directory i got everything working! Have a great day man!
