### ISSUE TITLE
Yuzu installation

### ISSUE THREAD

**Issue by Boosolomon** [Lincoln-LM/swsh-mods-exl#5]
I used the cheat code and it worked but i wanted the sound effect i have been trying to use the artifact in the mod location bit no results, can you pls tell me how to do it.

**Comment by KalyanRam2004** [comment]
which exact folder did u put the files into?

**Comment by Boosolomon** [comment]
In the mods file where you put the romfs folder, I used the code and it worked now I wanted to see if I can use the sound effect

**Comment by KalyanRam2004** [comment]
can u send me the location path. 
thanks :}

**Comment by KalyanRam2004** [comment]
for me they show up to enable or disable it but nothing works
are u using a new savefile by any chance,

**Comment by Lincoln-LM** [comment]
#9
