### ISSUE TITLE
hi guys please help me i can not install yuzu

### ISSUE THREAD

**Issue by ThatsMichl** [Lincoln-LM/swsh-mods-exl#6]
Hello people, can someone help me, I can't install the emulator
![image](https://github.com/user-attachments/assets/935499fe-abd2-49fa-aac3-fdbc7e44198d)

**Comment by Lincoln-LM** [comment]
The original yuzu repository was taken down from github. Find an archive or one of its derivatives, this is not the place to troubleshoot installing an emulator.
